In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4,5,6,7'
import yaml
import json
import torch
import torch.nn as nn
from tqdm import tqdm
import numpy as np
import utils.train_util as train_util
from dataloader.dataloader import TestingDataset,MultimodaFeaturesDataset
from src.loss.loss_compute import SimpleLossCompute
from src.model.baseline_model import Baseline
from src.loop.run_epoch import training_loop,validating_loop

config_path = './config/config.yaml'
config = yaml.load(open(config_path))
train_dataset = MultimodaFeaturesDataset(config['DatasetConfig'],job='training')
val_dataset = MultimodaFeaturesDataset(config['DatasetConfig'],job='valdation')
test_dataset = TestingDataset(config['DatasetConfig'])

/opt/conda/envs/pytorch_py3/lib/python3.6/site-packages/ipykernel/__main__.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.


In [2]:
train_dataset[0]

/opt/conda/envs/pytorch_py3/lib/python3.6/site-packages/transformers/tokenization_utils_base.py:2110: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


(tensor([[ 0.5063, -1.3404, -1.0076,  ..., -0.9102,  0.0265,  1.1618],
         [ 1.2224, -0.9595, -0.9289,  ..., -0.0388, -0.0936,  0.5921],
         [ 1.7696, -1.0206, -1.0104,  ...,  1.5784, -0.6792,  0.5998],
         ...,
         [ 1.8942, -0.9977, -0.9623,  ...,  0.8192, -0.7299,  0.7455],
         [ 1.7594, -0.8933, -0.9115,  ...,  0.5582, -0.9112, -0.2808],
         [ 1.5019, -0.5789, -1.0068,  ...,  0.8961, -0.6365,  0.9117]]),
 tensor([[ 1.1552, -1.7376,  0.2501,  ..., -0.4245,  0.0156,  6.6787],
         [ 0.7874, -1.8205,  1.2265,  ..., -0.0799, -0.3481,  6.8582],
         [ 0.7530, -1.6834,  1.3468,  ..., -0.7737, -1.6918,  5.6804],
         ...,
         [ 0.6713, -1.8014,  0.8079,  ...,  0.3014, -0.5942,  6.2051],
         [ 0.8289, -1.6909,  1.1255,  ...,  0.0485, -0.7019,  4.8522],
         [ 0.7106, -1.8769,  1.0616,  ...,  2.0977, -1.1343,  6.8735]]),
 tensor([ 101,  872, 2157, 7770,  704, 4495, 3221,  679, 3221, 6820, 1905,  754,
         6821, 3416, 4638, 7348, 36